### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by ernesst** [chesedo/glances-remote-scope#1]
Hello, 
While setting up your interesting scope i got an error. The scope found the server but doesn't show anything when i'm selecting an icon

```

[2016-03-01 23:00:09.190900] INFO: Registry: RegistryObject::ScopeProcess::on_process_death(): Process for scope: "glances-scope.chesedo_glances-scope" exited
aa_getcon failed, errno = 13
[2016-03-01 23:00:58.376492] INFO: Registry: RegistryObject::ScopeProcess::exec(): Process for scope: "glances-scope.chesedo_glances-scope" started
/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/node_modules/categories/resources.js:200
    header.add_attribute_value("title", result.title() + " - " + result.get("attributes")[0].value);
                                               ^

Error: expected an exported object
    at Error (native)
    at ResourcesCategory.createGeneralPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/node_modules/categories/resources.js:200:48)
    at ResourcesCategory.createPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/node_modules/categories/resources.js:185:18)
    at null.<anonymous> (/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/glances-scope.chesedo_glances-scope.js:140:63)
unity-js-scopes-launcher: /usr/include/boost/variant/detail/visitation_impl.hpp:207: typename Visitor::result_type boost::detail::variant::visitation_impl(int, int, Visitor&, VPCV, mpl_::true_, NBF, W*, S*) [with W = mpl_::int_<20>; S = boost::detail::variant::visitation_impl_step<boost::mpl::l_iter<boost::mpl::l_end>, boost::mpl::l_iter<boost::mpl::l_end> >; Visitor = boost::detail::variant::copy_into; VPCV = const void*; NBF = boost::variant<unity::scopes::internal::NullVariant, int, bool, std::basic_string<char>, double, std::map<std::basic_string<char>, unity::scopes::Variant>, std::vector<unity::scopes::Variant>, long long int>::has_fallback_type_; typename Visitor::result_type = void; mpl_::true_ = mpl_::bool_<true>]: Assertion `false' failed.
[2016-03-01 23:02:01.713742] INFO: Registry: RegistryObject::ScopeProcess::on_process_death(): Process for scope: "glances-scope.chesedo_glances-scope" exited
[2016-03-01 23:02:01.714169] ERROR: Registry: RegistryObject::ScopeProcess: Scope: "glances-scope.chesedo_glances-scope" closed unexpectedly. Either the process crashed or was killed forcefully.
aa_getcon failed, errno = 13
[2016-03-01 23:02:05.408905] INFO: Registry: RegistryObject::ScopeProcess::exec(): Process for scope: "eu.michael-weimann.stock-n-roll_stock-n-roll" started
got quote
addInfoCategory
onSearch → finishSearchReply
aa_getcon failed, errno = 13
[2016-03-01 23:02:08.094209] INFO: Registry: RegistryObject::ScopeProcess::exec(): Process for scope: "glances-scope.chesedo_glances-scope" started
/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/node_modules/categories/resources.js:231
        ["Read", data.convertByteRate(total["read_bytes"])],
                 ^

ReferenceError: data is not defined
    at ResourcesCategory.createDiskIOPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/node_modules/categories/resources.js:231:18)
    at ResourcesCategory.createPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/node_modules/categories/resources.js:188:18)
    at null.<anonymous> (/opt/click.ubuntu.com/glances-scope.chesedo/0.1/glances-scope/glances-scope.chesedo_glances-scope.js:140:63)


```

**Comment by chesedo** [comment]
Hi, thanks for reporting this.

Can you tell me which are all the icons that are shown?
And if the same happens in any of the other departments?

Also include the version of glances running on the remote machine.

**Comment by chesedo** [comment]
Never mind. Found the issue for the second error.

The first I'm not sure about yet as it relates to the Scope's API - which should therefore work. But will try a workaround.

**Comment by chesedo** [comment]
@ernesst can you test if this [click](https://github.com/chesedo/glances-remote-scope/raw/1-Connection-error/builds/glances-scope.chesedo_0.1.1_armhf.click) resolves the issue for you

**Comment by ernesst** [comment]
I could access to the sub menu, but soon after i got a blank screen in the scope

```
/opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/node_modules/categories/resources.js:257
    result.get("disksTable").forEach(function(disk) {
                             ^

TypeError: result.get(...).forEach is not a function
    at ResourcesCategory.createDiskIOPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/node_modules/categories/resources.js:257:30)
    at ResourcesCategory.createPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/node_modules/categories/resources.js:210:18)
    at null.<anonymous> (/opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/glances-scope.chesedo_glances-scope.js:142:63)
aa_getcon failed, errno = 13
[2016-03-02 20:03:05.966125] INFO: Registry: RegistryObject::ScopeProcess::exec(): Process for scope: "eu.michael-weimann.stock-n-roll_stock-n-roll" started
addBookmarksCategory error:TypeError: Cannot read property 'results' of undefined



```

**Comment by chesedo** [comment]
The above click has been updated. Can you test it again?

**Comment by ernesst** [comment]
Hello,

Still the same error for storage section 

```
opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/node_modules/categories/resources.js:258
    disksTable.forEach(function(disk) {
               ^

TypeError: disksTable.forEach is not a function
    at ResourcesCategory.createDiskIOPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/node_modules/categories/resources.js:258:16)
    at ResourcesCategory.createPreview (/opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/node_modules/categories/resources.js:210:18)
    at null.<anonymous> (/opt/click.ubuntu.com/glances-scope.chesedo/0.1.1/glances-scope/glances-scope.chesedo_glances-scope.js:142:63)

```

**Comment by chesedo** [comment]
Hi @ernesst, I am still on this bug - just waiting for a fix from [upstream](https://answers.launchpad.net/unity-js-scopes/+question/288084)

**Comment by chesedo** [comment]
@ernesst the click above has been updated again with the fixes if you would not mind testing it for me.

**Comment by chesedo** [comment]
Hi @ernesst, are you still able to test the fix?

**Comment by ernesst** [comment]
Pieter,

I'm travelling the following month, i will not able to test fix before May.

Regards

On Monday, March 28, 2016 11:20:57 AM CEST, Pieter 
notifications@github.com wrote:

> Hi @ernesst, are you still able to test the fix?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/chesedo/glances-remote-scope/issues/1#issuecomment-202318484

## 

Sent using Dekko from my Ubuntu device

**Comment by chesedo** [comment]
Np @ernesst

**Comment by chesedo** [comment]
@ernesst I've been able to get the package tested on a phone and all seems OK now.
